- include_tasks: get-cookie.yml
  when: viptela_api_cookie is not defined

- name: See if the controller exists
  uri:
    url: "https://{{ hostvars['vmanage1'].ansible_host }}/dataservice/system/device/controllers"
    method: GET
    headers:
      Cookie: "{{ viptela_api_cookie }}"
    validate_certs: "{{ validate_certs }}"
    return_content: yes
  register: uri_results
  delegate_to: localhost

- set_fact:
    controller_deviceIP_list: "{{ uri_results.json.data | map(attribute='deviceIP') | list }}"
    controller_hostname_list: "{{ uri_results.json.data | selectattr('host-name', 'defined') | map(attribute='host-name') | list }}"

- name: Add controller
  uri:
    url: "https://{{ hostvars['vmanage1'].ansible_host }}/dataservice/system/device"
    method: POST
    headers:
      Cookie: "{{ viptela_api_cookie }}"
    body_format: json
    body:
      deviceIP: "{{ device_ip }}"
      username: "{{ viptela_api_username }}"
      password: "{{ viptela_api_password }}"
      personality: "{{ device_personality }}"
      generateCSR: "{{ device_generateCSR | default('false') }}"
    validate_certs: "{{ validate_certs }}"
    return_content: yes
  register: controller_results
  changed_when: true
  delegate_to: localhost
  when: (device_ip not in controller_deviceIP_list) and (device_hostname not in controller_hostname_list)